### ISSUE TITLE
[Detection subsystem] base - technical planning

### ISSUE THREAD

**Issue by achoruzy** [industArk/omnirune#20]
Detection subsystem development have to be explored for possibilities, decided and planed for further works to provide sufficient base model for future experiments and on the other hand to be sufficient for building MVP product.

**Comment by industArk** [comment]
The biggest question is should we approach here with singular subsystem of detection + multi-classification using eg. YOLO model runned with openCV so what will be returned is already rune type classification, or just to classify if the window shows a rune or not; or different approach to use torch models with the same question.
